FROM nginx:alpine

#RUN mkdir /var/www/public -p && touch /var/www/public/index.php

RUN mkdir /var/www/html -p && touch /var/www/html/index.php

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx.conf.prod /etc/nginx/conf.d/default.conf
